config.py:
- __init__
- _clear_exposed_cache
- _is_state_exposed
- _log_invalid_automation
- _log_invalid_script
- _minimal_config
- async_invalidate_access_token
- authorized
- endpoint
- entity_config
- entity_id_to_number
- get_entity_name
- get_exposed_states
- is_reporting_states
- is_state_exposed
- locale
- number_to_entity_id
- set_authorized
- should_expose
- should_report_state
- supports_auth
- user_identifier
