google_config.py:
- _2fa_disabled_legacy
- __init__
- _async_exposed_entities_updated
- _handle_entity_registry_updated
- _migrate_google_entity_settings_v1
- _should_expose_entity_id
- _should_expose_legacy
- _supported_legacy
- agent_user_id
- cloud_user
- enabled
- entity_config
- get_agent_user_id
- get_local_agent_user_id
- get_local_webhook_id
- has_registered_user_agent
- secure_devices_pin
- should_2fa
- should_expose
- should_report_state
