config_entry.py:
- _async_connected_device_registered
- _async_register_mac
- add_to_platform_start
- battery_level
- device_info
- entity_registry_enabled_default
- find_device_entry
- force_update
- handle_device_event
- hostname
- ip_address
- is_connected
- latitude
- location_accuracy
- location_name
- longitude
- mac_address
- should_poll
- source_type
- state
- state_attributes
- unique_id
